INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'ALDECIA MENDES TENORIO', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'M', 'WALDEK FIDELIS CALHEIROS', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'MARIA LUIZA NUNES DE ALMEIDA', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'ELIANE FELIX DA SILVA', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'EDJA MARIA DE ANDRADE LYRA', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'MERCIA RENILDA BERNARDINO DO NASCIME', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'FERNANDA LAUREANA DA SILVA', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'OZELMA LUZIA CARLOS', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'M', 'MARCEL GARCIA DOS SANTOS', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'MYLENA GOMES ESPINDOLA', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'ROSIMERE BARANOSKI', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'MARIA JOSE MOREIRA FERNANDES', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'ALINE DA SILVA', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'M', 'RENAN GARCIA DE SOUZA', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'DANIELA ANGELO MEDEIROS', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'HELLEN CAMARGO PIEROBON', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'ROSENILDA DE OLIVEIRA SILVA', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'DANIELLE DUARTE DE GOIS', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'ALEXANDRA MARIA CAVALCANTE VITAL', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'KARINA ANGELICA GONZALEZ CADENA', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'ANA LUCIA SANTOS DA SILVA', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'ROUSE CRISTINE SOARES DE SANTANA', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'M', 'NATHAN RIBEIRO BARRETO', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'M', 'RICARDO MACHADO MENDES', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'ROMERO FARIAS FRANCA', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'EDNA PASSOS MENEZES', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'M', 'MILENO LUCIO SILVESTRE', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'MARIA LUIZA DOS SANTOS', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'MARIA DO SOCORRO SOARES', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'MICHELE SILVA SANTOS', 1);
INSERT INTO public.pessoa (id_pessoa, altura, ativo, data_de_nacimento, genero, nome, salario) VALUES (nextval('seq_pessoa'), 1, false, current_timestamp, 'F', 'MARIA HELENA HONORATO DA SILVA', 1);
INSERT INTO public.aplicacao (id_aplicacao, nome) VALUES(nextval('seq_aplicacao'), 'OK 1');
INSERT INTO public.aplicacao (id_aplicacao, nome) VALUES(nextval('seq_aplicacao'), 'OK 2');
INSERT INTO public.entidade (id_entidade, id_aplicacao, nome, rotulo, tabela) values (nextval('seq_entidade'), 1, 'pessoa1', 'Pessoa1', 'pessoa1');
INSERT INTO public.entidade (id_entidade, id_aplicacao, nome, rotulo, tabela) values (nextval('seq_entidade'), 1, 'pessoa2', 'Pessoa2', 'pessoa2');
INSERT INTO public.entidade (id_entidade, id_aplicacao, nome, rotulo, tabela) values (nextval('seq_entidade'), 2, 'empresa1', 'Empresa1', 'empresa1');
INSERT INTO public.entidade (id_entidade, id_aplicacao, nome, rotulo, tabela) values (nextval('seq_entidade'), 2, 'empresa2', 'Empresa2', 'empresa2');
